---
- name: Install PostgreSQL repository prerequisites
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - gnupg
    state: present
    update_cache: true

- name: Create PostgreSQL keyring directory
  ansible.builtin.file:
    path: /usr/share/postgresql-common/pgdg
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Download PostgreSQL repository signing key
  ansible.builtin.get_url:
    url: https://apt.postgresql.org/pub/repos/apt/ACCC4CF8.asc
    dest: /usr/share/postgresql-common/pgdg/apt.postgresql.org.asc
    mode: "0644"

- name: Configure PostgreSQL repository
  ansible.builtin.deb822_repository:
    name: pgdg
    types: deb
    uris: https://apt.postgresql.org/pub/repos/apt
    suites: "{{ ansible_facts['distribution_release'] }}-pgdg"
    components:
      - main
    signed_by: /usr/share/postgresql-common/pgdg/apt.postgresql.org.asc
    state: present
    enabled: true

- name: Install PostgreSQL
  ansible.builtin.apt:
    name:
      - "postgresql-{{ postgresql_version }}"
      - "postgresql-client-{{ postgresql_version }}"
    state: present

- name: Stop PostgreSQL service
  ansible.builtin.systemd:
    name: postgresql
    state: stopped
    enabled: false
